### ISSUE TITLE
Path conflicts in ./config

### ISSUE THREAD

**Issue by iamdadmin** [pushpak1300/Larasonic#18]
The folder ./config is being used by both the Laravel app, Frankenphp, and as XDG_CONFIG_HOME.

This results in an unclear/inconsistent storage.

I'd suggest either:

1. Laravel app uses config, and all other paths are set under ./docker/storage/ i.e. ./docker/storage/xdg_config, ./docker/storage/caddy-data, ./docker/storage/caddy-config or another folder, either way one single folder outside the usual laravel project structure to avoid conflicts
2. Laravel app moves into a subfolder of ./app or similar, and you create folders for caddy and XDG in the root

**Comment by iamdadmin** [comment]
This would be a simple fix, if it helps:
```yaml
    environment:
      XDG_CONFIG_HOME: /var/www/caddy-config
      XDG_DATA_HOME: /var/www/caddy-data
```
Caddy and PsyShell (Tinker) will both use XDG_CONFIG env var, alternatively PsyShell can be given a config file
```yaml
    environment:
      PSYSH_CONFIG: /var/www/html/tinker.config.php
```
In this config file you can set:
```php
<?php

return [
    'historyFile' = '/var/www/psysh_history';
];
```
If you want them to persist outside the container, make a folder, I am assuming it can be `../Larasonic-storage` so it lives in the parent folder on the local file system but naming it with Larasonic to keep them together/linked
```yaml
    environment:
      XDG_CONFIG_HOME: /storage/caddy-config
      XDG_DATA_HOME: /storage/caddy-data
      PSYSH_CONFIG: /var/www/html/tinker.config.php
    volumes:
      - '../Larasonic-storage:/storage'
```
and change tinker.config.php as follows
```php
<?php

return [
    'historyFile' = '/storage/psysh/psysh_history';
];
```
